name:         periodic_table
version:      0.1.1
author:       Herman Bergwerf <hermanbergwerf@gmail.com>
description:  The Periodic Table of Elements data as Dart package
homepage:     https://github.com/bergwerf/periodic-table
environment:
  sdk:        '>=1.8.0 <3.0.0'
